# Case Study: Organic Foods and Poor Morals {#CaseOrganic}

"You are what you eat" is a common phrase dating back to at least the 1820's used to suggest that if you want to be fit, you must eat healthy foods.  However, does the phrase extend to our personality as well as our physique?  Recent research has suggested that specific tastes (sweet vs. disgusting, for example) can influence moral processing.  That is, certain foods may lead us to be nicer to those around us or lead us to be more judgemental.  Organic foods are often marketed using phrases like "pure" or "honest" (Jessica Alba's [Honest Company](https://www.honest.com/), for example); is there some relationship between the consumption of organic foods and moral behavior?

Dr. Eskine of the Department of Psychological Sciences at Loyola University sought to answer this question.  She conducted a study to investigate whether exposure to certain types of food had an effect on a person's moral processing.

Specifically... (describe study)

A group of researchers wanted to replicate Dr. Eskine's work.  They ... (describe study).  

(Present Data)...

(Add References)
