# Nature of Collecting Multivariable Data {#Regdata}

For the [Seismic Activity Case Study](#CaseGreece), we are primarily interested in characterizing the relationship between bracketed duration and the magnitude of the earthquake.  As we discussed in the previous chapter, this general goal might be refined into one of many specific questions:

  - In general, does the bracketed duration increase as the magnitude increases?
  - If two earthquakes with different magnitudes occur in the same location, would we expect the same bracketed duration regardless of their magnitudes?
  - Is the relationship between the bracketed distance and the magnitude different depending on the soil condition of where the measurement is taken?
  
Notice that these last two questions actually require knowledge of more than just the braketed duration and the magnitude of each seismic event.  In order to address the second question, we would also need the distance from the center of the earthquake; in order to address the third question, we also need the soil conditions of where the measurement is taken.  Often, research questions require knowledge of more than just two variables; such questions are __multivariable__.

```{definition, label=defn-multivariable, name="Multivariable"}
Refers to questions of interest which involve more than a single variable.  Often, these questions involve many variables.
```

Consider going to the doctor because you are feeling ill.  The doctor does not have you simply enter your most prominent symptom (fever, for example) into a computer and then prescribe a medication based solely on that single symptom.  Instead, a good physician will review all symptoms you are experiencing, as well as your medical history, other medications, allergies, etc.  The physician operates in a multivariable world in which there are many contributing factors to a response.  Therefore, when you arrive for this hypothetical visit, they record several variables which may be of interest.  

Studies which collect several variables can be observational studies or controlled experiments.  If an observational study, we ensure the sample of subjects is representative of the population.  Then, for each individual, we simply record several variables.  If a controlled experiment, we would randomly assign subjects to a particular group; afterwards, we would measure the response in addition to other variables.  Notice that with the latter, subjects are randomly assigned to only one of the variables; the remaining variables are simply observed.  As in Chapter \@ref(ANOVArecap), if our primary predictor of interest in a secondary study is not the variable to which the subjects were randomly assigned, we must treat the study as observational.

What we want to emphasize here is that how we collect the data has not really changed from what we have discussed in previous units.  The primary difference is that we are very aware that we are collecting several measurements on each subject.  The critical element is that our sample be representative of the population if we want to apply any findings to the population.
